---
version: "3.9"
services:
  ddclient:
    image: linuxserver/ddclient:latest
    container_name: ddclient
    hostname: ddclient
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Indiana/Indianapolis
    volumes:
      - ./config:/config
    networks:
      - ddclient
    restart: unless-stopped
networks:
  ddclient:
    name: ddclient
    ipam:
      config:
        - subnet: "172.16.0.0/24"
          gateway: "172.16.0.1"
